### ISSUE TITLE
Cannot use "-" sign in query

### ISSUE THREAD

**Issue by gmiejski** [jexp/neo4j-shell-tools#116]
When using "-" sign in cypher, the tool thinks you're trying to add another option and returns error "Unrecognized option 'xxx'.

For example when you want to use where clause like node.property > -1 - this will throw error "Unrecognized option '1'"

Haven't yet looked into code yet, but seems trivial fix to stop parsing options after first not option.

**Comment by gmiejski** [comment]
Could you make a quick test and check if the problem comes from neo4j AppCommandParser or not?

**Comment by jexp** [comment]
Which feature do you use? Could you use APOC within Cypher to achieve the same?

**Comment by gmiejski** [comment]
So old I dont remember what was it about. Closing.
