### ISSUE TITLE
order of arguments is important in graphml export 

### ISSUE THREAD

**Issue by alperyilmaz** [jexp/neo4j-shell-tools#117]
Hi,
In Linux, `export-graphml` expects the order of arguments in certain order. The README document [says](https://github.com/jexp/neo4j-shell-tools/blame/1700f6478296f90d2bf1465f56e39f3f6275301a/readme.md#L287) that `export-graphml [-o out.graphml] [-t] [-r] [match (n:Foo)-[r]->() return n,r]` is how the command should be issued. 
However when I run that way, I get error:

```
$ export-graphml -o out.graphml -t -r MATCH (n)--(p) WHERE p.count=0 AND n.count <> 0 RETURN n,p
QueryExecutionException: Invalid input '-': expected <init> (line 1, column 1 (offset: 0))
"-r MATCH (n)--(p) WHERE p.count=0 AND n.count <> 0 RETURN n,p"
 ^
```

But, when I change the order of arguments it works without problem.

```
$ export-graphml -t -r -o out.graphml MATCH (n)--(p) WHERE p.count=0 AND n.count <> 0 RETURN n,p
```
I thought this should be mentioned in README file.. Thanks..

**Comment by alperyilmaz** [comment]
And I'm guessing the issue #114 is also about the order of argument. The user kept the order as mentioned in README file and got error.

**Comment by jexp** [comment]
Thanks a lot @alperyilmaz I'll change it now.
