### ISSUE TITLE
Neo4J 2.0 Support

### ISSUE THREAD

**Issue by aloysius-lim** [jexp/neo4j-shell-tools#15]
Tried installing this into the 2.0 M4 release, but it does not even load into neo4j-shell. The import commands are not available, no error messages and nothing in the logs (as far as I can tell) to indicate what the problem might be. Tried on both Mac OS X 10.7 and CentOS 6. 

2.0 support would be great, as I would very much like to work with labels. Any pointers as to what the issue might be would be good too, so I can help to find a fix. Thanks.

**Comment by jexp** [comment]
I have to do that in a separate branch, but will look into it. We have to compile a version for 2.0.

**Comment by ghost** [comment]
Are the shell-tools working on 2.0?

**Comment by jexp** [comment]
Yep, check the 2.0 branch: https://github.com/jexp/neo4j-shell-tools/tree/20
