### ISSUE TITLE
Which file folder to be used for import script ?

### ISSUE THREAD

**Issue by FTHKramer** [jexp/neo4j-shell-tools#16]
Dears,
under Win XP the proposed examples does not work for me. Result is:
...
neo4j-sh (0)$ import-graphml -i in.xml
==> Cannot open file in.xml for reading.
...
I guess Java filereader method does not find the file unter name "in.xml". How to do absolute file path under XP and where is Java looking for only "in-xml" ?

Thanks for support!

FTHKramer, Toulouse

**Comment by jexp** [comment]
Is the file in the current folder?

Otherwise you can try a full path?

**Comment by rvanbruggen** [comment]
I had to look for this as well, on OSX. I believe it looks for input files under the neo4j home directory (where you installed neo4j).

**Comment by FTHKramer** [comment]
Thanks for quick response.
This is funny ... Which folder.is current folder in NEO4J ?
I guess the server configuration should explain which folder structure is used for that (for doing imports or to understand where Java will looking for this first.. I have put the import file meanwhile in nearly all available folders for getting this information ... Shell answer remains the same
So I need to re-compile the JAR file for printing out the current folder ?
Sounds strange ;-)

Best regards

**Comment by jexp** [comment]
Or just provide an absolute path.

**Comment by FTHKramer** [comment]
Thanks for support. The default folder is that one below the /bin. There must be a space between file name and semicolon for the extended Neo4J. Best regards. I think we can close.
