### ISSUE TITLE
Line-number in errors

### ISSUE THREAD

**Issue by puredevotion** [jexp/neo4j-shell-tools#18]
Hi,

Could you add a line number whenever the GEOFF import finds an error? That makes debugging my GEOFF files a lot easier :)

**Comment by jexp** [comment]
Don't know if geoff itself reports them, ping @nigelsmall

**Comment by technige** [comment]
The neo4j-geoff code doesn't process line-by-line so it could be quite hard to add. But feel free to put in a PR if you can find a good way to do it. You probably want to start here:

https://github.com/neo4j-contrib/neo4j-geoff/blob/master/geoff-core/src/main/java/org/neo4j/geoff/store/TokenReader.java

**Comment by puredevotion** [comment]
I'm unfortunately not good enough in Java that I can be of any decent help.
I do see that UeberReader and TokenReader provide the unexpected character `ch` with the error messages. Maybe we can show those in the import-tools? That would already be very helpful, I think

In TokenReader.Java:
`throw new UnexpectedCharacterException(ch);`

Interestingly, in https://github.com/neo4j-contrib/neo4j-geoff/blob/master/geoff-core/src/main/java/org/neo4j/geoff/except/SubgraphError.java there is a rulenumber. Not sure if rule = line...

**Comment by technige** [comment]
A rule is a node or relationship element but doesn't necessarily correspond to line.

I don't have any time to look at this I'm afraid. Maybe someone on the mailing list would be willing to give it a try.

**Comment by puredevotion** [comment]
I Don't think this is anything of high priority. I just noticed it. A simple work around is making a small file to test it with, then implement at large.

**Comment by jexp** [comment]
Have a PR here: https://github.com/nigelsmall/geoff/pull/3
