### ISSUE TITLE
Unparsable JSON in rule on valid JSON

### ISSUE THREAD

**Issue by puredevotion** [jexp/neo4j-shell-tools#19]
I'm trying to import GEOFF files, but I get the error:
`Unparsable JSON in rule`

I checked my JSON with JSONlint (http://jsonlint.com/), and it should be valid. 

My GEOFF rule looks like: 

`(1 :0gram {"word":"a", "rank":5228, "prob":0.0175865, "gram":"0gram", "nid":1})`

I tried making the float a string, all numbers a string, but it always returns the unparsable JSON error. I had spaces between the keys/values, but that wasn't it either.

I know it fails on either the above JSON, or the one below, because I made a stupid typo: `(1)-[:FOLLOWED_BY]->(2")` and it didn't provide the `RuleFormatException: Syntax error in rule` error that it should have, would the parser have reached that line.

second GEOFF line:

`(2 :1gram {"word":"model", "rank":"36", "prob":"0.0068860", "gram":"1gram", "nid":"2"})`

Maybe this is in GEOFF, and not in your import script?

**Comment by puredevotion** [comment]
I did some further testing, and installed the Load2Neo plugin (http://nigelsmall.com/load2neo), which Nigel Small refers to as the "reference Geoff parser implementation".

Load2Neo has no trouble loading the JSON...

**Comment by jexp** [comment]
Probably because the import-tools use an older version, and something might have changed in between?

Have to check.

The identifiers with leading numbers are no problem?

**Comment by puredevotion** [comment]
No, I first had `(1:0gram {"..."})` and gave a RuleFormatException, once I got the space in there (`(1 :0gram {"..."})`) it went on fine.

**Comment by jexp** [comment]
Fixed by integrating the new geoff 0.5.0 from @nigelsmall
