### ISSUE TITLE
I can't use neo4j-shell, doesn't work command import-graphml

### ISSUE THREAD

**Issue by CrazyUmka** [jexp/neo4j-shell-tools#25]
I follow step instruction, but i get unknown command: import-graphml
Please, help me

**Comment by jexp** [comment]
Without any details I can't help you.

Please specify exactly what you did.

**Comment by CrazyUmka** [comment]
Hi. It's working. This is magic. What other methods to import graphml file exist?

**Comment by jexp** [comment]
Cool, what did you change? There is another blueprints based importer I think, and you can export neo4j-store files from gephi.

**Comment by CrazyUmka** [comment]
Maybe I did something wrong. I reinstall neo4j, install tools and all working. How can I have a value of type string edge change the int?

**Comment by CrazyUmka** [comment]
i need to cast edge.value = '124567' to int via cypher query. It's possible?

**Comment by jexp** [comment]
toInt() was added to Neo4j 2.1

**Comment by CrazyUmka** [comment]
HI, how can I find the degree of a node? Example: I get section graph by means of cypher:
start n = node(1, 2, 3, 4, 5 ,6)
Match (n)-[r*..2]-(c)
return *
How i can degree node this graph and if degree is less than a specified number then don't get this node? This is possible?

**Comment by jexp** [comment]
This belongs in a question on StackOverflow or the google group, not in a github issue.

Nevetheless:

```
start n = node(1, 2, 3, 4, 5 ,6)
Match (n)-[r*..2]-(c)
return c, length((c)--()) as degree
```

To filter it:

```
start n = node(1, 2, 3, 4, 5 ,6)
Match (n)-[r*..2]-(c)
with c, length((c)--()) as degree
where degree > 2
return c
```

**Comment by CrazyUmka** [comment]
Thank you)
