### ISSUE TITLE
export-graphml output cannot be imported to database with import-graphml command

### ISSUE THREAD

**Issue by Fresbee** [jexp/neo4j-shell-tools#30]
Operating System:  Ubuntu 12.04 LTS
Neo4j version:  2.0.1

When running the export-graphml command in the neo4j shell-tools console, it can return extra properties that should not exist in the <data> tags of a node or an edge. This prevents you from importing a generated graphml file into Neo4j.  

Here is a sample graph that I created with these Cypher statements:

```
CREATE (dog:Pet{species: "Dog", breed: "Irish Setter"})
CREATE (cat:Pet{species: "Cat", breed: "Siamese"})
CREATE (bird:Pet{species: "Bird", breed: "Canary"})
CREATE (dog)-[:CHASES{frequency: "sometimes"}]->(cat)
CREATE (cat)-[:CHASES{frequency: "often"}]->(bird)
```

I used this command to export the graph into GraphML form:

```
neo4j-sh (?)$ export-graphml -o outputTest.graphml -t
```

After running the above export-graphml command, here is the output I see:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
<graph id="G" edgedefault="directed">
<key id="breed" for="node" attr.name="breed" attr.type="string"/>
<key id="species" for="node" attr.name="species" attr.type="string"/>
<key id="frequency" for="edge" attr.name="frequency" attr.type="string"/>
<node id="n76" labels=":Pet"><data key="labels">:Pet</data><data key="species">Dog</data><data key="breed">Irish Setter</data></node>
<node id="n77" labels=":Pet"><data key="labels">:Pet</data><data key="species">Cat</data><data key="breed">Siamese</data></node>
<node id="n78" labels=":Pet"><data key="labels">:Pet</data><data key="species">Bird</data><data key="breed">Canary</data></node>
<edge id="e370" source="n76" target="n77" label="CHASES"><data key="label">CHASES</data><data key="frequency">sometimes</data></edge>
<edge id="e371" source="n77" target="n78" label="CHASES"><data key="label">CHASES</data><data key="frequency">often</data></edge>
</graph>
</graphml>
```

Notice that for each node there is a key="labels" property called ":Pet".  Also notice that for each edge there is a key="label" called "CHASES" (the relationship type).  This is redundant information, since these values are contained in the node/edge tag properties.  This poses a problem when you have to import-graphml this created GraphML file into Neo4j.

Here is the result of trying to re-import this GraphML file:

```
neo4j-sh (?)$ import-graphml -i /opt/neo4j-community-2.0.1/petGraph.graphml
GraphML-Import file /opt/neo4j-community-2.0.1/petGraph.graphml rel-type RELATED_TO batch-size 40000 use disk-cache false
finish after 7 row(s)  0. 100%: nodes = 1 rels = 0 properties = 0 time 23 ms total 23 ms
null
```

These extra data properties prevent you from importing/exporting the same data.

**Comment by jexp** [comment]
Thanks for raising the issue.

**Comment by Fresbee** [comment]
No problem.  Could you let me know when you implement a fix?  I'm unsure if I have GitHub set to alert me when a commit occurs on a project.

**Comment by jexp** [comment]
Can't promise any fix soonish. I try to find time. Do you see any exceptions?

Can you start the shell with -v and test it again?

**Comment by jexp** [comment]
Should be fixed, please check and report back.

**Comment by Fresbee** [comment]
I tested the fix and I am able to import data from the previously exported GraphML file.  However, there is a caveat.  There is redundant information that is generated when you export a Neo4j database.  Perhaps I didn't specify this, but a node has it's labels listed in both the starting node tag, as well as a separate XML data tag.

Example of an exported node.  I thought that the labels should only be contained in the start node tag after node id="n5093".  You will see a data key="labels" containing the exact same information:

``` xml
<node id="n5093" labels=":Pet"><data key="labels">:Pet</data><data key="species">Dog</data><data key="breed">Irish Setter</data></node>
```

This is an issue, since the node's labels will be included as a node property upon an import-graphml command.  That occurs because they listed as a data key just as the "species" and "breed" properties are.  The "Dog" node will have these values as properties:

```
labels  :Pet
species Dog
breed   Irish Setter
```

Similarly, the graph edges have the same issue.  I thought that the relationship type should only be contained in the start edge tag after target="n5094".  You will see a data key="label" containing the exact same information as in the starting edge tag:

``` xml
<edge id="e9532" source="n5093" target="n5094" label="CHASES"><data key="label">CHASES</data><data key="frequency">sometimes</data></edge>
```

This is the same issue; the relationship type will be included as a property on the edge after doing an import-graphml command.  That occurs because the relationship type is a data key just as the "frequency" property is in this example.  This edge will contain the following properties upon import:

```
frequency   sometimes
label   CHASES
```

I used the same dataset as shown at the top of this thread.  Please let me know if I can further help.

**Comment by jexp** [comment]
Oh sorry, I thought I skip the labels data key for properties on import. I have to fix it for relationships that's true.

Did you specify the new -t option on import ?

**Comment by Fresbee** [comment]
I didn't see that you added the -t command flag for import-graphml.  Using this command flag, import-graphml now successfully imports the "Pet" label to all 3 nodes.  There is no "labels" property on the nodes when -t is used.

As you mentioned, -t does not handle the label property for relationships.  

In the readme.md file, you may want to update the command line options for import-graphml.  It has -t REL_TYPE, when it should read -r REL_TYPE.  Here is the currently displayed text in readme.md:

```
import-graphml [-i in.xml] [-t REL_TYPE] [-b 20000] [-c]
```

**Comment by jexp** [comment]
I updated and pushed.

**Comment by Fresbee** [comment]
I verified the fix.  When I use the import-graphml -i [name of .graphml file] -t, the graph is correctly imported.  Labels are applied and there are no extra properties for node labels or relationship type.  I closed the issue.  Thank you for your hard work on the shell tools.  I'm happy to help suggest improvements to the Neo4j ecosystem.

**Comment by jexp** [comment]
Cheers :)
