### ISSUE TITLE
Is there any way to script the use of shell tools?

### ISSUE THREAD

**Issue by SimonShapiro** [jexp/neo4j-shell-tools#31]
Hi,

I really like shell tools!

Is there anyway to script their use.  My use case is to have a browser app that will let people export and import the grapheml files?

Regards

**Comment by jexp** [comment]
If you blog about it, I tell you how ;)

**Comment by SimonShapiro** [comment]
Hmm.

I don’t blog regularly, do you have a site you would like me to make the entry.

I am really enjoying neo4j!

My use case is to condition the general network capability via a meta model.  Then there is a general html5 browser that generates forms that follow the metamodel.  I need to script the tools in order to provide the functionality of multiple databases.  So to save a snapshot version of the network, I would make it a graphml, empty the network db and load the next one.

I have neo4j now running on aws.  

I am currently trying to get my app onto heroku.

Best wishes

Simon

**Comment by jexp** [comment]
Sure you can script it, you can commands to neo4j-shell or use `neo4j-shell -c commands`
You can also use a file with the commands and use `neo4j-shell -file file.neosh`
