### ISSUE TITLE
Error in exporting database to graphml

### ISSUE THREAD

**Issue by roots-ai** [jexp/neo4j-shell-tools#39]
I am getting the following error while exporting the database to graphml...

```
RuntimeException: org.neo4j.kernel.impl.nioneo.store.InvalidRecordException: Next block set[10939579] current block illegal size[1048696/120]
```

Any idea how to resolve this?

**Comment by jexp** [comment]
Sounds like your db has inconsistent data? Does it happen with other operations too?

Please run the consistency checker on your db and report back to the neo4j google group.
see here:
http://www.markhneedham.com/blog/2014/01/22/neo4j-backup-store-copy-and-consistency-check/
