### ISSUE TITLE
GraphML export for selected subgraph (with cypher) not working

### ISSUE THREAD

**Issue by zhiboz** [jexp/neo4j-shell-tools#40]
Thanks for this great tool! I was trying to use the capability to export a subgraph into graphml, with no success.

README suggests to use this syntax as follows, but it did not work for me.

neo4j-sh (?)$ export-graphml -o out.graphml -t -r match (n:Foo)-[r]->() return n,r
SyntaxException: Invalid input '(': expected <init> (line 1, column 1)
"(n:Foo)-[r]->() return n,r"
 ^

Did I use it incorrectly?

**Comment by jexp** [comment]
What does not work for you there? Does it output an empty file?

**Comment by zhiboz** [comment]
Sorry I did not make myself clear. I updated my initial post to include the error message. I guess the issue is that I could not figure out the right syntax. Thanks!

**Comment by jexp** [comment]
Good question, lemme check :)

**Comment by caligolaz** [comment]
Same problem here :-(

**Comment by jonaslund** [comment]
Same here. No updates?

**Comment by mel18** [comment]
I have the same issue. "SyntaxException: Invalid input '(': expected <init> (line 1, column 1 (offset: 0))" What am I doing wrong?

**Comment by jexp** [comment]
@mel18 I just pushed a branch with an update to 2.2

**Comment by jexp** [comment]
Taken from a test `export-graphml -r -o target/test.xml match(n)-[r]->() return n,r`

**Comment by jexp** [comment]
Or this `export-graphml -t -r -o target/test.xml match (n:FOO)-[r]->() return n,r`

**Comment by jexp** [comment]
```
export-graphml -t -r -o target/test.xml match (n:Foo)-[r]->() return n,r
Wrote to GraphML-file target/test.xml 0. 100%: nodes = 2 rels = 1 properties = 2 time 2 ms total 2 ms
```

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
<graph id="G" edgedefault="directed">
<key id="name" for="node" attr.name="name" attr.type="string"/>
<node id="n0" labels=":Foo"><data key="labels">:Foo</data><data key="name">bar</data></node>
<node id="n1" labels=":Bar"><data key="labels">:Bar</data><data key="name">foo</data></node>
<edge id="e0" source="n0" target="n1" label="REL"><data key="label">REL</data></edge>
</graph>
</graphml>
```

**Comment by zhiboz** [comment]
Thanks for the fix! Exporting works now.

When trying to load it with networkx in python 

``` python
g = nx.read_graphml('/tmp/test.xml')
```

the following error occurs

``` bash
networkx.exception.NetworkXError: Bad GraphML data: no key labels
```

**Comment by mel18** [comment]
@jexp Thanks for pushing the update. Now I am receiving the error:  "NotInTransactionException: The statement has been closed." after the export has been running for a few hours. The results file is empty. I've checked the query, that doesn't seem to be the problem. I apologize if this is the wrong spot to ask the question about this error, I wasn't sure where to post. If I should post elsewhere, please let me know. Thank you.

Also, if I run a smaller export, by using limit, it does complete. Im guessing it has to do with the size of the data from the query.

**Comment by jexp** [comment]
what does your statement look like? And how long does it run if your run it standalone? And for instance just `RETURN COUNT(*)`

**Comment by mel18** [comment]
I apologize, I think it may be another issue, not related the the shell tools. Sorry.

**Comment by chiddianozie** [comment]
Hi @zhiboz, how did you resolve the issue of Bad GraphML data: no key labels

**Comment by raymondbernard** [comment]
Trying to import GraphML Getting=   Bad GraphML data: no key labels!!!

I exported neo4j using neo4j-shell. It works. but I cannot import what I exported.

**Comment by jexp** [comment]
Can you please try it with APOC ? https://github.com/neo4j-contrib/neo4j-apoc-procedures
It has an apoc.export.graphml procedure which should have these issues fixed.

https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_graphml_import_export

**Comment by diegodaudt** [comment]
I'm still getting  _Bad GraphML data: no key labels_  with APOC
:(
