### ISSUE TITLE
Import from cvs of an array property fail [neo4j-community-2.1.3]

### ISSUE THREAD

**Issue by caligolaz** [jexp/neo4j-shell-tools#41]
I've tried with this simple statement
import-cypher -i /Applications/neo4j-community-2.1.3/datasources/products.csv -d ; -q  -b 5000 create(n:Item{sku:{sku},category:[{category}]})

This is the csv:
"sku";"category"
"8185089";"1742,2094,5452,5456,15117,15136"
"5092403";"2652,13934"

When i try to access to the array from chypher with this command
MATCH (i:Item)
return i.category[0] limit 5

I get a string and not an array.
If i try to create the same statement ,via neo4j browser application, all works perfecly.

**Comment by jexp** [comment]
I think you have to do a split on the array value

```
create(n:Item{sku:{sku},category:split({category},",")})
```
