### ISSUE TITLE
XMLStreamException on import-graphml

### ISSUE THREAD

**Issue by saurabh-p** [jexp/neo4j-shell-tools#43]
I exported the neo4j-database in graphml format but while importing back the database at the production server I am getting the following error.
`XMLStreamException: ParseError at [row,col]:[2542885,95]
Message: An invalid XML character (Unicode: 0x8) was found in the element content of the document.`

But there is no such character on line number 2542885.

I even deleted this line using `sed -i (2542885d)` but I am still getting the same error at the same line while importing. Strange.

It seems the line number which sed is referring to is not the same as the line at which the error is been thrown.

Please help out, I have spent a day to resolve this error. But no success.

**Comment by jexp** [comment]
Did you try an xml valdiator with the exported file?
Perhaps you can share the exported file privately with me?

**Comment by saurabh-p** [comment]
Thank you. Error resolved.
I used xmllint, which gave the same error at another line number, and replacing that unicode character resolves the issue.
