### ISSUE TITLE
export-graphml is not exporting keys properly

### ISSUE THREAD

**Issue by rnix** [jexp/neo4j-shell-tools#51]
For the keys that specify graph, node, edge, ... properties, the [GraphML Specification](http://graphml.graphdrawing.org/specification/element_key.xsd.htm) states

> These functions are declared by &lt;key&gt; elements (children of &lt;graphml&gt;)

In the output of `export-graphml`, the `<key>` elements are incorrectly children of the first `<graph>` element (which is itself a child of `<graphml>` making the `<key>` elements descendants of `<graphml>` but not children.)

**Comment by buhrmann** [comment]
Also, the "labels" key is missing. To make the exported file work with, say, the networkx library, first the key elements have to be moved manually to the right position (see above) and then a "labels" key added.
