### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by Dazzid** [jexp/neo4j-shell-tools#58]
The manual installation doesn't work. git clone git@github.com:jexp/neo4j-shell-tools.git 
gives as a result:
Cloning into 'neo4j-shell-tools'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

How can i access to the file? The traditional way is not working for me either. 
Thanks

**Comment by Dazzid** [comment]
OK! resolved :)

**Comment by jexp** [comment]
Use the http git url:
https://github.com/jexp/neo4j-shell-tools.git
