### ISSUE TITLE
Easier installation

### ISSUE THREAD

**Issue by kengz** [jexp/neo4j-shell-tools#72]
To make it easier to install this tool, can we add the following commands that searches for the `lib/` path and extracts the zip automatically into it? It's better than the users manually searching the path each time when they set this up. 

The same shell script also works for MacOS and Linux. It searches the Kernel StoreDirectory for the lib path, set it as `NEO4J_HOME`, then call `curl` to download and unzip into `${NEO4J_HOME}lib`

``` shell
NEO4J_HOME=$(neo4j-shell -c 'dbinfo -g Kernel StoreDirectory' | grep -oE '\/.*lib.*?\/') && curl -LOk http://dist.neo4j.org/jexp/shell/neo4j-shell-tools_2.2.zip && unzip neo4j-shell-tools_2.2.zip -d ${NEO4J_HOME}lib
```

**Comment by jexp** [comment]
Good idea, can you send a pull request for such an install script?
