### ISSUE TITLE
Running export-graphml returns null

### ISSUE THREAD

**Issue by tjwright** [jexp/neo4j-shell-tools#84]
I am trying to export a database in graphml using the neo4j-shell-tools. However when I run the command: 

`export-graphml [-o out.graphml] [-t]`

as outlined in this post here: https://inserpio.wordpress.com/2014/02/10/how-to-load-neo4art-graph-db-into-gephi/

The neo4j-shell just returns 'null' and an empty out.graphml file.

**Comment by jexp** [comment]
the things in square brackets are just examples you have to remove the square brackets

export-graphml -o out.graphml
